version: '3.3'
services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    image: darkdfg/foodgram_backend:latest
    volumes:
      - static_value:/backend/static/
      - media_value:/backend/media/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: darkdfg/foodgram_frontend:latest
    volumes:
      - ./foodgram-project-react/frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./foodgram-project-react/frontend/build/:/usr/share/nginx/html/
      - ./foodgram-project-react/docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
        - frontend
        - backend
volumes:
  postgres_data:
  static_value:
  media_value:
  